version: '3'
services:
  app:
    build: .
    container_name: design-components_app
    volumes:
      - ./app:/app
      - node_modules:/app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    stdin_open: true 
    tty: true

volumes:
  node_modules: