version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    working_dir: /app
    stdin_open: true 
    tty: true
